version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: db_postgres_discord
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: discord
      POSTGRES_PASSWORD: discord
      POSTGRES_DB: discorddb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - discord_network

  adminer:
    image: adminer:latest
    container_name: adminer_container
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - discord_network

volumes:
  postgres_data:


networks:
  discord_network:
